workflows:
  expo-prebuild-android:
    name: Expo (prebuild) → Android APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      node: 18
      npm: 9
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Generate native android/ with Expo prebuild
        script: |
          npx expo prebuild --platform android --no-install
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/**/*.apk
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - node_modules
