// contexts/LanguageContext.tsx
import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

type LangKey = "en" | "si" | "ar" | "ta" | "hi" | "ur";
type LangOption = { key: LangKey; name: string; rtl?: boolean };
type Dict = Record<string, string>;
type Dictionaries = Record<LangKey, Dict>;

/** 🔹 All strings live here (no external JSON). */
const dictionaries: Dictionaries = {
  en: {
    loading: "Loading…",
    language: "Language",
    welcome: "Welcome",
    subtitle: "your intilegent shopping companion",
    search: "Search",
    scanImage: "Scan Image",
    voiceOrder: "Voice Order",
    scanBarcodeQR: "Scan Barcode / QR",
    "scan BarcodeQR": "Scan Barcode / QR",
    "market": "Market",
    assistant: "AI Assistant",
    quickAccess: "Quick Access",
    wishlist: "Wishlist",
    help: "Help",
    settings: "Settings",
    about: "About",
    cart: "Cart",
    marketPlace: "Market Place",
    comingSoonTitle: "Coming soon",
    comingSoon: "This page will be added next.",
    permission: "Permission",
    cameraPermissionRequired: "Camera permission is required",
    smartImageScanner: "Smart Image Scanner",
    imageSearch: "Image Search",
    sampleResult: "This is a sample result.",
    noImageSelected: "No image selected",
    takePhoto: "Take photo",
    chooseFromGallery: "Choose from gallery",
    findSimilarItems: "Find similar items",
    tips: "Tips",
    tipClearFront: "Keep the item clearly in front",
    tipGoodLight: "Use good lighting",
    tipAvoidBusyBg: "Avoid busy backgrounds",
    searchProducts: "Search Products",
    searchPlaceholder: "Search...",
    recentSearches: "Recent Searches",
    noResults: "No results found for",
    voiceSearch: "Voice Search",
    offers: "Offers",
  },
  si: {
    loading: "පූරණය වෙමින්…",
    language: "භාෂාව",
    welcome: "ආයුබෝවන්",
   subtitle: "ඔබගේ බුද්ධිමත් වෙළඳ  සහකරු ",
    search: "සොයන්න",
    scanImage: "පිංතූර ස්කෑන්",
    voiceOrder: "හඬින් ඇණවුම",
    scanBarcodeQR: "බාර්කෝඩ් / QR",
    "scan BarcodeQR": "බාර්කෝඩ් / QR",
    "market": "වෙළඳපොළ", 
    assistant: "AI ආධාරක",
    quickAccess: "ක්වික් ප්‍රවේශ",
    wishlist: "Wish List",
    help: "උදව්",
    settings: "සැකසුම්",
    about: "අප ගැන",
    cart: "කරත්තය",
    marketPlace: "වෙළඳපොළ",
    comingSoonTitle: "ඉක්මනින්",
    comingSoon: "මේ පිටුව ඊළඟට එක් කරමු.",
    permission: "අවසරය",
    cameraPermissionRequired: "කාමරා අවසරය අවශ්‍යයි",
    smartImageScanner: "Smart Image Scanner",
    imageSearch: "පිංතූර සෙවුම",
    sampleResult: "උදාහරණ ප්‍රතිඵලයකි.",
    noImageSelected: "පිංතූරයක් තෝරාගෙන නැහැ",
    takePhoto: "ඡායාරූපය ගන්න",
    chooseFromGallery: "ගැලරියෙන් තෝරන්න",
    findSimilarItems: "සමාන භාණ්ඩ සොයන්න",
    tips: "ඉඟි",
    tipClearFront: "භාණ්ඩය පැහැදිලිව ඉදිරියෙන් තබන්න",
    tipGoodLight: "හොඳ ආලෝකය භාවිතා කරන්න",
    tipAvoidBusyBg: "වැඩි පසුබිම් වලින් වැලකෙන්න",
    searchProducts: "භාණ්ඩ සොයන්න",
    searchPlaceholder: "සොයන්න...",
    recentSearches: "මෑත සෙවීම්",
    noResults: "ප්‍රතිඵලයක් නැහැ",
    voiceSearch: "හඬ සෙවුම",
    offers: "ඇසෝදු",
  },
  ar: {
    loading: "…جاري التحميل",
    language: "اللغة",
    welcome: "مرحبًا",
    subtitle: "رفيق التسوّق الذكي الخاص بك",
    search: "بحث",
    scanImage: "مسح صورة",
    voiceOrder: "طلب صوتي",
    scanBarcodeQR: "مسح باركود / QR",
    "scan BarcodeQR": "مسح باركود / QR",
    "market": "سوق", 
    assistant: "مساعد ذكي",
    quickAccess: "وصول سريع",
    wishlist: "المفضلة",
    help: "مساعدة",
    settings: "الإعدادات",
    about: "حول",
    cart: "سلة",
    marketPlace: "السوق",
    comingSoonTitle: "قريبًا",
    comingSoon: "سيتم إضافة هذه الصفحة لاحقًا.",
    permission: "إذن",
    cameraPermissionRequired: "يلزم إذن الكاميرا",
    smartImageScanner: "ماسح الصور الذكي",
    imageSearch: "بحث بالصور",
    sampleResult: "نتيجة تجريبية.",
    noImageSelected: "لا توجد صورة محددة",
    takePhoto: "التقاط صورة",
    chooseFromGallery: "اختيار من المعرض",
    findSimilarItems: "اعثر على عناصر مشابهة",
    tips: "نصائح",
    tipClearFront: "ضع العنصر بوضوح أمام الكاميرا",
    tipGoodLight: "استخدم إضاءة جيدة",
    tipAvoidBusyBg: "تجنّب الخلفيات المزدحمة",
    searchProducts: "ابحث عن المنتجات",
    searchPlaceholder: "ابحث...",
    recentSearches: "عمليات البحث الأخيرة",
    noResults: "لا توجد نتائج لـ",
    voiceSearch: "بحث صوتي",
    offers: "عروض",
  },
  ta: {
    loading: "ஏற்றுகிறது…",
    language: "மொழி",
    welcome: "வணக்கம்",
    subtitle: "உங்கள் புத்திசாலி ஷாப்பிங் துணை",
    search: "தேடல்",
    scanImage: "பட ஸ்கேன்",
    voiceOrder: "குரல் ஆர்டர்",
    scanBarcodeQR: "பார்கோட் / QR",
    "scan BarcodeQR": "பார்கோட் / QR",
    assistant: "உதவியாளர்",
    "market": "மார்க்கெட்",
    quickAccess: "விரைவு அணுகல்",
    wishlist: "விருப்பப் பட்டியல்",
    help: "உதவி",
    settings: "அமைப்புகள்",
    about: "பற்றி",
    cart: "வண்டி",
    marketPlace: "மார்க்கெட்",
    comingSoonTitle: "விரைவில்",
    comingSoon: "இந்தப் பக்கம் பின்னர் சேர்க்கப்படும்.",
    permission: "அனுமதி",
    cameraPermissionRequired: "கேமரா அனுமதி தேவை",
    smartImageScanner: "ஸ்மார்ட் இமேஜ் ஸ்கேனர்",
    imageSearch: "படத் தேடல்",
    sampleResult: "மாதிரி முடிவு.",
    noImageSelected: "படம் தேர்ந்தெடுக்கப்படவில்லை",
    takePhoto: "புகைப்படம் எடு",
    chooseFromGallery: "கேலரியில் இருந்து தேர்வு செய்",
    findSimilarItems: "ஒத்த பொருட்களை கண்டுபிடி",
    tips: "உதவிக்குறிப்புகள்",
    tipClearFront: "பொருளை தெளிவாக முன்புறம் வையுங்கள்",
    tipGoodLight: "நல்ல ஒளி பயன்படுத்துங்கள்",
    tipAvoidBusyBg: "அலட்டலான பின்னணிகளை தவிர்க்கவும்",
    searchProducts: "பொருட்களைத் தேடுங்கள்",
    searchPlaceholder: "தேடுங்கள்...",
    recentSearches: "சமீபத்திய தேடல்கள்",
    noResults: "முடிவுகள் இல்லை",
    voiceSearch: "குரல் தேடல்",
    offers: "சலுகைகள்",
  },
  hi: {
    loading: "लोड हो रहा है…",
    language: "भाषा",
    welcome: "नमस्ते",
    subtitle: "आपका स्मार्ट शॉपिंग साथी",
    search: "खोजें",
    scanImage: "छवि स्कैन",
    voiceOrder: "वॉइस ऑर्डर",
    scanBarcodeQR: "बारकोड / QR",
    "scan BarcodeQR": "बारकोड / QR",
    assistant: "एआई सहायक",
    "market": "मार्केट",
    quickAccess: "त्वरित पहुँच",
    wishlist: "इच्छा सूची",
    help: "सहायता",
    settings: "सेटिंग्स",
    about: "जानकारी",
    cart: "कार्ट",
    marketPlace: "मार्केट",
    comingSoonTitle: "जल्द आ रहा है",
    comingSoon: "यह पेज बाद में जोड़ा जाएगा।",
    permission: "अनुमति",
    cameraPermissionRequired: "कैमरा अनुमति आवश्यक है",
    smartImageScanner: "स्मार्ट इमेज स्कैनर",
    imageSearch: "चित्र खोज",
    sampleResult: "नमूना परिणाम।",
    noImageSelected: "कोई तस्वीर चुनी नहीं गई",
    takePhoto: "फोटो लें",
    chooseFromGallery: "गैलरी से चुनें",
    findSimilarItems: "समान आइटम ढूंढें",
    tips: "टिप्स",
    tipClearFront: "वस्तु को स्पष्ट रूप से सामने रखें",
    tipGoodLight: "अच्छी रोशनी का उपयोग करें",
    tipAvoidBusyBg: "व्यस्त पृष्ठभूमि से बचें",
    searchProducts: "उत्पाद खोजें",
    searchPlaceholder: "खोजें...",
    recentSearches: "हाल की खोजें",
    noResults: "कोई परिणाम नहीं",
    voiceSearch: "वॉइस खोज",
    offers: "ऑफ़र",
  },
  ur: {
    loading: "لوڈ ہو رہا ہے…",
    language: "زبان",
    welcome: "خوش آمدید",
   
    search: "تلاش",
    scanImage: "تصویر اسکین",
    voiceOrder: "وائس آرڈر",
    scanBarcodeQR: "بارکوڈ / QR",
    "scan BarcodeQR": "بارکوڈ / QR",
    assistant: "اسسٹنٹ",
    "market": "مارکیٹ",
     quickAccess: "فوری رسائی",
    wishlist: "پسندیدہ",
    help: "مدد",
    settings: "سیٹنگز",
    about: "متعلق",
    cart: "کارٹ",
    marketPlace: "مارکیٹ پلیس",
    comingSoonTitle: "جلد آرہا ہے",
    comingSoon: "یہ صفحہ بعد میں شامل کیا جائے گا۔",
    permission: "اجازت",
    cameraPermissionRequired: "کیمرہ اجازت درکار ہے",
    smartImageScanner: "سمارٹ امیج اسکینر",
    imageSearch: "تصویری تلاش",
    sampleResult: "نمونہ نتیجہ.",
    noImageSelected: "کوئی تصویر منتخب نہیں",
    takePhoto: "تصویر کھینچیں",
    chooseFromGallery: "گیلری سے منتخب کریں",
    findSimilarItems: "مشابہ اشیاء تلاش کریں",
    tips: "مشورے",
    tipClearFront: "شے کو واضح طور پر سامنے رکھیں",
    tipGoodLight: "اچھی روشنی استعمال کریں",
    tipAvoidBusyBg: "مصروف پس منظر سے گریز کریں",
    searchProducts: "مصنوعات تلاش کریں",
    searchPlaceholder: "تلاش کریں...",
    recentSearches: "حالیہ تلاشیں",
    noResults: "کوئی نتیجہ نہیں",
    voiceSearch: "وائس تلاش",
    offers: "آفرز",
  },
};

const languageOptions: LangOption[] = [
  { key: "en", name: "English" },
  { key: "si", name: "සිංහල" },
  { key: "ar", name: "العربية", rtl: true },
  { key: "ta", name: "தமிழ்" },
  { key: "hi", name: "हिन्दी" },
  { key: "ur", name: "اردو", rtl: true },
];

type Ctx = {
  t: (k: string) => string;
  lang: LangKey;
  setLang: (l: LangKey) => void;
  languages: LangOption[];
  isRTL: boolean;
  isReady: boolean;
};

const LanguageCtx = createContext<Ctx | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<LangKey>("en");
  const [isReady, setReady] = useState(false);

  useEffect(() => setReady(true), []);

  const isRTL = useMemo(() => languageOptions.find(o => o.key === lang)?.rtl === true, [lang]);

  /** 🔸 Lookup with graceful fallbacks (space-insensitive alt key). */
  const t = (k: string) => {
    const dict = dictionaries[lang] || dictionaries.en;
    const en = dictionaries.en;
    const alt = k.replace(/\s+/g, "");
    return dict[k] ?? dict[alt] ?? en[k] ?? en[alt] ?? k;
  };

  const value: Ctx = { t, lang, setLang, languages: languageOptions, isRTL, isReady };
  return <LanguageCtx.Provider value={value}>{children}</LanguageCtx.Provider>;
}

export function useLanguage(): Ctx {
  const ctx = useContext(LanguageCtx);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
